#!/bin/bash
while :; do
cd /root/spr
./tnn --broadcast --tune-duration 1 --threads 4 --spectre --stratum --daemon-address spr.tw-pool.com --port 14001 --wallet spectre:qzfsfrg4t8053a8n25hvwwr2l6kgmvgk7qepm07gwhdmsnvkvjdws5pcq36rv --worker-name stb1 --dev-fee 1 --quiet
sleep 3
done
