#!/bin/bash
while :; do
cd /root/tnn
./tnn --tune-duration 1 --threads 4 --spectre --daemon-address 192.168.1.10 --port 5555 --wallet spectre:qqe5wgm6a98097n5mnjp2ngjkjh3e4ljzrj8rtmzfduwp5r9dmm6kum0kjy9l --dev-fee 1 --quiet
sleep 3
done
