#!/bin/bash

while :; do
cd /root/luna
./deroluna --api-listen 0.0.0.0:44001 -t 4 -w dero1qyrsdymxexmqm3n4fxmwcmtp03utu60eu0r877qat20v76m5u9wkjqq6uw3dv.STB -d dero-node-orionure-sg.mysrv.cloud:10300 --no-colors --restart-on-zero-hashrate
sleep 3
done
