#!/bin/bash
while :; do
cd /root/astro
./astrominer -zero-hr-restart-time 5 -report-realtime-hashrate -ft -1 -k -1 -show-latency -log-interval 60 -no-watchdog -opmem -w dero1qyrsdymxexmqm3n4fxmwcmtp03utu60eu0r877qat20v76m5u9wkjqq6uw3dv -r 154.26.138.136:10100 -r1 dero-node-orionure-sg.mysrv.cloud:10100
sleep 3
done
